site_name: Docker MkDocs

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Maintainer Guide: maintainer-guide.md
  - Tools:
    - DockerHub: dockerhub.md
    - Git: git.md
    - Docker: docker.md
    - Poetry: poetry.md
    - Dive: dive.md
  - License: license.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/hackforla/docker-mkdocs
repo_name: hackforla/docker-mkdocs
edit_uri: edit/main/docs/

plugins:
  - search
  - autolinks

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      url_download: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      title: On this page
      permalink: true

watch:
  - README.md
  - LICENSE
